Dockerfile

App runner deployment is still failing as alembic directory is not copied correctly.

Fixing dockerfile.

---

docker-compose.yml
makefile-docker.defs

Docker compose now is only for development - so remove the dependency the backend has on open search... and add a makefile command to just start the backend.

Add start_backendonly i.e. without Opensearch

---

app/api/api_v1/routers/lookups/config.py
app/api/api_v1/schemas/metadata.py
app/core/ingestion/family.py
app/core/ingestion/processor.py
app/core/organisation.py
app/data_migrations/data/keyword_data.json
tests/core/ingestion/test_metadata.py
tests/core/ingestion/test_validate_row.py
tests/core/validation/test_util.py
tests/routes/test_config.py

New return from `/config` when using the query param `group_documents=True` - Similar to the other endpoint so we are able to support both the old style and new style endpoints.
In the case of `group_document` being enabled (new style) - the return value includes the orgainisation and the taxonomy:
```
{
organisation: "...",
taxonomy: { ... }
}
``` 
Includes new test.
Adds a keyword too - see https://climate-policy-radar.slack.com/archives/C02ET708QDP/p1677672962069199?thread_ts=1676476399.009199&cid=C02ET708QDP

Use taxonomy on /config when group_documents=True

---

app/api/api_v1/routers/documents.py
app/api/api_v1/schemas/document.py
app/db/crud/document.py
tests/routes/test_documents.py

- import_id included for families and documents
- document slug can now be used to return a document object + family context

Return a FamilyDocument from /documents when using a doc slug

---

scripts/validate_cclw_sheet/download.py

Use the new Master sheet for validating daily

Update CCLW master sheet reference

---

app/db/crud/document.py
tests/routes/test_documents.py

Traceback of the error experienced in the backend code: 
AttributeError: 'Language' object has no attribute 'code'
This error comes from the following line:
https://github.com/climatepolicyradar/navigator-backend/blob/main/app/db/crud/document.py#L105 

Bugfix - Fixing Attribute Error 

---

app/api/api_v1/schemas/document.py
app/db/crud/document.py
tests/routes/test_documents.py

- Return a list of family slugs that are in a collection - when the `/documents` endpoint is called with a doc slug
```
{
"organisation": "CCLW",
"import_id": "CCLW.family.1001.0",
"title": "Fam1",
"summary": "Summary1",
"geography": "GEO",
"category": "Executive",
"status": "Published",
"metadata": {
"topic": [
"Mitigation"
],
"hazard": [],
"sector": [
"Energy"
],
"keyword": [
"Energy Supply"
],
"framework": [],
"instrument": [],
"document_type": "Order"
},
"slugs": [
"FamSlug1"
],
"events": [
{
"title": "Published",
"date": "2019-12-25T00:00:00+00:00",
"event_type": "Passed/Approved",
"status": "Ok"
}
],
"published_date": "2019-12-25T00:00:00+00:00",
"last_updated_date": "2019-12-25T00:00:00+00:00",
"documents": [
{
"import_id": "CCLW.executive.1.2",
"variant": "MAIN",
"slugs": [ …
```

Add family slugs as a property on collections

---

alembic/versions/0013_families_and_collections.py
app/core/ingestion/metadata.py
app/data_migrations/__init__.py
app/data_migrations/data/document_role_data.json
app/data_migrations/populate_document_role.py
app/data_migrations/populate_document_type.py
app/data_migrations/populate_taxonomy.py
app/db/models/law_policy/__init__.py
app/db/models/law_policy/family.py
app/initial_data.py
tests/core/ingestion/test_metadata.py
tests/routes/test_config.py
tests/routes/test_documents.py

- change the schema with the new table FamilyDocumentRole
- populate the values in `init_data`
- also populate the values for FamilyDocumentType
- relax the FK to be nullable for both type and role

BAK-1330 Add document role, add values in init_data

---

app/api/api_v1/routers/admin.py
app/api/api_v1/routers/unauthenticated.py
app/core/ratelimit.py
app/main.py
poetry.lock
pyproject.toml
tests/routes/test_unauthenticated.py

Remove rate limiting for API endpoints as part of load testing.
The rate limiting is not fit for purpose (restricting calls only on a single process), so this will not be re-added. Rate limiting will instead be implemented at the infrastructure level.

Remove rate limiting from API calls

---

app/core/browse.py
tests/routes/test_search.py

Browse without grouping should return opensearch formatted dates

Browse without grouping should return opensearch formatted dates

---

app/core/search.py
tests/routes/test_search.py

Search results need to be in opensearch format for non-grouped results

Search results need to be in opensearch format for non-grouped results

---

app/api/api_v1/routers/admin.py
app/api/api_v1/schemas/document.py
app/core/ingestion/ingest_row.py
app/core/ingestion/physical_document.py
app/core/ingestion/pipeline.py
app/core/search.py
app/core/validation/util.py
app/db/crud/document.py
app/db/models/document/physical_document.py
app/db/models/law_policy/family.py
tests/core/ingestion/test_physical_document.py
tests/core/ingestion/test_pipeline.py
tests/core/validation/test_util.py
tests/routes/document_helpers.py
tests/routes/test_documents.py
tests/routes/test_search.py

Generate a full view of the current document database that should be visible in Opensearch. This is used to detect changes & update indexed information used in searches.
Also includes a change to provide multiple document languages to the frontend.
Existing tests updated & extended, new tests for generated document list.

Write document state to s3 to trigger pipeline

---

app/core/util.py

Add "navigator/" prefix to CDN object names when building complete URLs to match the new document bucket structure.

Add "navigator/" prefix to CDN URLs

---

app/core/ingestion/pipeline.py

When writing pipeline input, a null document type was causing failures to trigger the pipeline. This change fixes that issue by using a default of `""` if no document type exists.

Default document type to empty string in pipeline input when not set

---

app/db/crud/document.py
app/db/models/law_policy/family.py

This change orders events according to their date, and removes a few db queries that have subsequently become unnecessary after ORM changes.
Any regressions are already covered by existing tests, although an explicit test for event ordering might be useful.

Order family events in API response & remove unnecessary queries

---

.github/funcs.sh
.github/retag-and-push.sh
.github/tests/test_retag_and_push.bats

- Makes the docker tags that are generated testable - by pulling this out into `funcs.sh` and writing tests for them.
- Fix the docker tag names when there is no maturity in the tag, by checking for this in `get_patch` and `get_maturity`
Using the written tests - **we still need to test on a tag**

WIP SOF-16 Change tagging to allow blank maturity

---

app/api/api_v1/routers/unfccc_ingest.py
app/api/api_v1/schemas/document.py
app/core/ingestion/pipeline.py
app/core/ingestion/processor.py
app/core/ingestion/unfccc/ingest_row_unfccc.py
app/core/ingestion/utils.py
tests/core/validation/test_util.py
tests/routes/test_admin_unfccc.py

Adds `download_url` into the file of documents for the pipeline

SOF-40 Add document_url for the pipeline

---

app/core/validation/__init__.py

Update ID match regex to match non party doc ids (e.g. `UNFCCC.non-party.123.0`)

Fix ID match regex in backend

---

app/core/ingestion/metadata.py
tests/routes/test_admin_cclw.py

When firing a document and event set of csvs at a locally deployed latest version of the backend with the latest production postgres db dump using the cclw ingest end point, the request fails.
This is as the metadata taxonomy values do not have allow_any values in the mapping. Here is an example after loading the latest production db state dump: 
"topic":{"allow_blanks":true,"allowed_values":["Mitigation","Adaptation","Loss And Damage","Disaster Risk Management"]}
This is causing the following error during the cclw ingest: 
```
{
"written_at":"2023-06-05T12:33:22.085Z",
"written_ts":1685968402085789000,
"msg":"Unexpected error, validating law & policy CSV on ingest",
"type":"log",
"logger":"app.api.api_v1.routers.cclw_ingest",
"thread":"AnyIO worker thread",
"level":"ERROR", …
```

TDD - approach to ingest bug 

---

app/core/ingestion/metadata.py
app/data_migrations/populate_taxonomy.py

Really minor fix to TaxonomyEntry typing & initial data loading to allow `make start` without errors.
Existing tests sufficient

Minor fix to TaxonomyEntry type & initial data loading

---

app/core/search.py
tests/routes/test_search.py

Previous fix did not correctly identify when the content of a document matched a given search term. This is no longer the case.
Existing tests updated after testing that regressions would be caught.

Minor CSV download content fix

---

.env.example
app/api/api_v1/routers/search.py
app/core/search.py
app/db/crud/document.py
tests/routes/test_search.py

- Makes the DocumentExtraCache TTL configurable
- Extends an existing tests and adds a new one to test when documents are marked as deleted
- Does not return families that are not Published
Also fixes tests that don't re-create the db ...
- tests/routes/test_search.py::test_sensitive_queries 
- tests/routes/test_search.py::test_accents_ignored

PDCT-179: Ensure search does not return families that are not Published

---

app/api/api_v1/schemas/search.py
app/core/search.py
tests/routes/test_search.py

Text page & Coords are not supplied for HTML documents, this was causing internal server errors when searching indices containing information about HTML documents.
Additional test added that queries an HTML index. Confirmed that this test acts as a regression test.

PDCT-196: Fix internal server error when searching html index

---

app/api/api_v1/routers/admin.py
app/db/models/document/physical_document.py
tests/routes/test_document_families.py

The current backend code assumes that language codes send to the update document endpoint will be if the for iso-639-3. This is a three letter representation of the language. 
The pipeline identifies languages as iso-639-1 which is a two letter representation. 
Thus, the endpoint is updated to handle the differing language codes. A unit test is also added to check functionality. 
NOTE: 
Should we update the languages table to enforce part1_codes being unique and len(2) as the functionality will rely on that an in practice the two letter codes should be unique and two letters (the same of language codes and three letters)? 
Should we also at least log when we pass over a language update due to it not existing in the database? 
[Linear …

Making updates to handle different iso codes.

---

app/db/crud/document.py

Sets default document cache timeout to 1-day rather than 1-minute. This should reduce the huge overhead on search requests that we've been seeing.

Set default document cache timeout to 1-day rather than 1-minute

---

docs/api/search.md

Closes PDCT-478
Adds the google doc sent to OEP as markdown - see PDCT-434

Add API search doc as markdown

---

app/api/api_v1/schemas/search.py
tests/unit/app/schemas/test_schemas.py

Updating the pydantic object for a search response that is utilised by the vespa conditional flow for a search response. 
The update is to add a root validator method that increments the passage match page number by one. 
Added some explicit tests to assert that the response objects correctly convert the index of the page to the required page number. This should help us should we upgrade pydantic etc. 
The plan is once merged to deploy to staging and verify via the api.

Adding one to vespa passage match pages.

---

app/core/search.py

Three families with zero events currently exist in the database. The opensearch version of this code handles this scenario, this adds the same for Vespa. See Linear for details on which families.
[
](https://linear.app/climate-policy-radar/issue/PDCT-609/fix-500-errors-for-certain-search-terms-with-vespa)
I recreated the issue locally by amending the test database setup and running `test_process_vespa_search_response` with no events. I wanted to leave a test covering this but havent been able to as the database setup is not flexible …

Handle vespa search errors from families with no events 

---

app/api/api_v1/routers/search.py
app/api/api_v1/schemas/search.py
tests/unit/app/schemas/test_schemas.py

Addition of a method to the SearchResponse class to increment that pages on the document passage matches. 
Unit tests that assert the method works correctly.

Pages Bug fix attempt no.2.

---

app/api/api_v1/routers/search.py
app/core/search.py
poetry.lock
pyproject.toml
tests/core/test_search.py
tests/routes/test_admin_unfccc.py

This is a bug relating to QueryErrors being thrown when a country or other filter is used against the api. 
This fix incorporates a new version of the dal that has been updated to expect a different set of filter fields. 
These fields effectively are what is actually used in vespa. 
This means we have to update the filter fields prior to validation of the SearchParameter object. 

Adding in the bugfix for the filter fields. 

---

app/core/config.py
app/core/search.py
tests/core/test_search.py

These values where previously hardcoded, so despite this being supported by the data access library interface with vespa, and the backend api accepting parameters for these, they would nevertheless always get set to the same values.
This passes those api parameters through to the data access library, and uses the previous set values as actual upper limits —— which we still need because of limiting excessive compute and avoiding timeouts.
See notion page for more context: https://www.notion.so/climatepolicyradar/Brief-10-matches-per-doc-100-documents-per-search-8f440121f9f44907b6ab99060f757412 …

Allow setting `max_hits` and `limit` for vespa

---

app/core/config.py
app/core/search.py
tests/core/test_search.py
tests/routes/test_vespasearch.py

Because of the way the backend processes the limit and offset values we ended up only ever getting ten results (aka the value of limit), this this turns out to be because we limit in the vespa query and then limit again in the result. Switching instead to have a fixed vespa limit resolves this issue until we can move limits to the vespa query

Fix pagination bug

---

tests/routes/setup_search_tests.py
tests/routes/test_vespasearch.py

For an upcoming pipeline infrastructure change, we needed to know how the backend might behave if there is data in just one of our two databases. This adds two exploratory tests, one covering when there is a document in postgres but not vespa, and the other checking the reverse — in vespa but not postgres. 
Both scenarios still return the correct documents, and a 200 response code. However, it turns out there is some impact on the backend for each:
- The document will still appear in browse (which seems fine)
- The hits will still be returned based on vespa content as vespa assumes postgres will find the data. There is potential for this to impact pagination as the frontend uses this number to determine how many pages to display.
- The backend logs errors that look like this: `ERROR …

Add tests to covering disparity between databases

---

app/api/api_v1/routers/search.py
tests/routes/setup_search_tests.py
tests/routes/test_vespasearch.py

Previously a bug fix attempted to resolve the fact that postgres and
vespa use different titles for fields. However it has led to keyword_filters
being preprocessed more than once for vespa and not at all for browse.

Fix keyword filter handling

---

Makefile
app/api/api_v1/routers/search.py
app/core/aws.py
app/core/config.py
app/core/download.py
app/core/health.py
pyproject.toml
tests/conftest.py

- Updated download route to redirect to CDN link instead of returning a streaming response
- Fixed bug where blank file was being uploaded to S3 due to not resetting buffer position
- Return 404 if we can't find the file at the absolute CDN path
- Converted SQL query to use Python string concatenation rather than multi-line string that seemed to be causing empty results
- Added time range to query to only dump documents that were last modified (or created) during all previous ingets cycles, so we exclude the current ingest cycle
- Linear ticket [here](https://linear.app/climate-policy-radar/issue/PDCT-788/redirect-to-cdn-instead-of-streaming-response)

Pdct 788/redirect to cdn instead of streaming response

---

app/api/api_v1/routers/pipeline_trigger.py
app/initial_data.py
app/main.py
poetry.lock
pyproject.toml

Triggers the db state file creation endpoint every monday at 9:15. This means we can run during work hours for the time being as we grow in confidence in the pipeline run, later it can be moved to run overnight instead.
The implementation is intended to be simple and is likely to be moved to a seperate service from the backend in the future.
@diversemix pointed me towards [fastapi-scheduler](https://github.com/amisadmin/fastapi-scheduler), I ended up using [apscheduler](https://github.com/agronholm/apscheduler) instead as it is what the former depends on for scheduling, so we can remove some complexity. Happy to be challenged on this if there might be a reason I missed to stick with the former.
- any additional …

Automatically run the pipeline on a weekly schedule

---

app/api/api_v1/routers/pipeline_trigger.py
app/core/ingestion/pipeline.py

The Depends interface relies on a request to function, which doesn't work for tasks triggered by a cron job. This works around that limitation.
Ran locally

Fix broken imports for ingest trigger

---

app/api/api_v1/routers/search.py
app/core/search.py
poetry.lock
pyproject.toml
tests/core/test_search.py
tests/routes/test_vespasearch.py

This surfaces the changes from the data access library: https://github.com/climatepolicyradar/data-access/pull/141
As part of that it also fixes an issue with country & region searches, where country codes from both would be combined into one, so we'd always get the whole region, rather refining within it.
Note that there was two functions handling this logic, one for search and another for browse (which had no tests), I've partially consolidated them but had to add a workaround until we come back and do this properly.
Please describe …

Make filters exclusive to each other

---

.gitignore
Dockerfile
app/api/api_v1/schemas/document.py
poetry.lock
pyproject.toml

Fast api & fastapi-pagination where also emitting some, as was pytest on some invalid config. Updating them has seemed to fix the issue. I tried to remove torch as it was emitting a warning and we aren't using it directly, it'll take a bit more work to remove though as it is used by other dependencies. However, I have removed torchvision so thats a start at least.

Reduce warnings from dependencies when running tests

---

app/api/api_v1/schemas/search.py
app/core/browse.py
app/core/search.py
tests/core/test_search.py
tests/routes/test_vespasearch.py
tests/unit/app/schemas/test_schemas.py

`total_family_hits` at the root of the response object is the full amount of families matched in vespa. Each family then has `total_passage_hits`, which is all the text matches

Add family and passage counts to backend response

---

app/main.py

We had the problem where three of these jobs started at the same time,
likely because there where three backend instances running at the time
due to the backend being at its scaling limit. The thinking is when the
parent process forks it is also brings the cron job with it.
The hope here is that moving it to the startup will cause it to only run
once. As an extra check this also adds an id and sets the job to replace
any existing jobs with that id.
It's hard to test this to know if it will work for sure, but it is
already broken, and if it turns out this still doesnt work I'll just
switch back to triggering it manually until there is enough time to do a
better solution
Please describe the tests that you added to verify your …

Move cron job to startup

---

app/api/api_v1/routers/pipeline_trigger.py
app/main.py

We are moving this cron trigger out of the backend because of a problem with cron jobs being duplicated across scaling instances that resulted in multiple ingests being triggered

Remove cron from backend

---

app/api/api_v1/schemas/search.py
app/core/search.py
poetry.lock
pyproject.toml
tests/core/test_search.py
tests/routes/test_vespasearch.py

See DAL changes for more: https://github.com/climatepolicyradar/data-access/compare/v0.5.2...v0.5.3
Note that the DAL release also includes an update that improves search sorting by switching it to use vespa instead of post processing the results

Add previous `continuation_token` to search response

---

app/api/api_v1/schemas/search.py

Taking this out led to the default behavior in the data access library.
This in turn led to a server error for the backend, but only under the
very specific circumstance that this parameter was missing and
continuation tokens where being used in the query.

Make query string required for backend

---

makefile-docker.defs

- Adds `vespa_setup` to `make start`
- Add optional arguments for test commands
Makes it possible to run specific tests with the following (rather than changing the file and accidently commiting it all the time):
`make test ARGS='-k test__convert_filters'`
Alternatively:
`make test ARGS='tests/core/test_search.py::test__convert_filters[None-None]'`

Improve local test running experience

---

app/core/search.py
tests/core/test_search.py

Makes the keyword filter parsing treat `{}` the same as `None`. Otherwise we end up filtering out valid results

Don't filter on empty filters

---

app/api/api_v1/schemas/metadata.py
app/core/organisation.py
tests/routes/test_config.py

In addition to the existing taxonomy - also add the corpus info with its taxonomy too.
Notes:
Please describe …

PDCT-1057 step1 - add corpus info to config

---

.trunk/trunk.yaml
app/api/api_v1/routers/geographies.py
app/db/crud/geography.py
pyproject.toml
tests/non_search/app/geographies/setup_world_map_helpers.py
tests/non_search/app/geographies/test_world_map_summary.py

Use family_status instead of doc_status in world map geo endpoint
Notes:
Please describe the tests that you …

Feature/pdct 1001 use family_status instead of doc_status in world map geo endpoint

---

app/api/api_v1/routers/search.py
pyproject.toml

Fixes QueryErrors in `create_vespa_search_params` not being caught by the exception handling, this resulted in a confusing 500 rather than a more informative 400
Notes:
used -- …

Fix 500 errors

---

app/core/health.py
pyproject.toml

Previous version ensured the instance had been deployed, but not that we could query it. Running an actual query checks for bad credentials, as pyvespa will raise an error on response codes between 400 and 599. The query in used here would work regardless of schema, and as it asks for 0 hits runs extremely fast
Notes:
- If you are …

Add a healthier vespa health check

---

tests/conftest.py

Longer running test runs where routinely seeing the error:
```
sqlalchemy.exc.ResourceClosedError: This Connection is closed
```
We previously had the connection shared across the whole test run, which is faster than starting a new connection each time, unfortunatly it seems to be leading to an issue with the session closing prematurely. To fix the issue, this moves the connection to be created on a per test function basis.
The tradeoff is this slows a full test run with `make test` down slightly (10-20s), but this seems better than them not working.
Please select the option below that is most …

Move session to function scope

---

app/core/search.py
pyproject.toml
tests/search/test_vespasearch.py

Some rows managed to find extra fields leading to a hard failure. This changes the behaviour in this situation to simply ignore the extra fields.
Also added a test that simulates missing fields by emptying out the list of expected fields so we can confirm it still passes
Notes:
- If none of these options are …

Ignore extra fields in csv export

---

app/api/api_v1/schemas/metadata.py
app/core/lookups.py
app/core/organisation.py
poetry.lock
pyproject.toml
tests/non_search/app/documents/test_get_document_families.py
tests/non_search/app/geographies/test_world_map_summary.py
tests/non_search/app/lookups/test_config.py
tests/unit/app/core/test_organisation.py

- bump db-client version
- fixup tests - the tests do seem fragile as they are based on the ids being deterministic - we should change this
Notes:
Please select the …

PDCT-1234 Fixes for the entity counter to allow new corpus

---

app/api/api_v1/schemas/search.py
pyproject.toml

- fixes the document search download by making document type an optional on SearchResponseFamilyDocument schema
- related PR comment: (https://github.com/climatepolicyradar/navigator-backend/pull/297/files/3dc6244ab53e0a9683b99e652253474655b53226#diff-7b9d7ebe61ff06fad1625a8f06a0efdbc1b4d9f6103470fdcf9ce54f2facde5c)
Notes:
- If you are …

Make document type on SearchResponseFamilyDocument schema optional

---

.github/workflows/ci-cd.yml
app/core/ingestion/pipeline.py
app/core/lookups.py
app/core/search.py
app/db/crud/document.py
pyproject.toml
tests/core/test_lookups.py

The pipeline trigger was failing due to a validation error on the document type:
```
1 validation error for DocumentParserInput
type
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
```
There was an update last week to how we determine the document type. It seems there are situations when this can evaluate to None. Here we extract the logic into its own function so we can apply a fix and test various conditions.
This approach might also be made more generalisable to extract any metadata field. I've left this for someone else as I'm just trying to fix the pipeline trigger
Visit the [Semver …

Fix retrieving document type from metadata

---

app/api/api_v1/schemas/document.py
pyproject.toml
tests/core/test_lookups.py
tests/non_search/core/validation/test_util.py

Somehow we are still getting None's passed to the pipeline trigger in production. This adds type coercion to the actual model.
Notes:
Please select the option(s) below …

Force `DocumentParserInput` type to be string

---

poetry.lock
pyproject.toml

Bump db client version to 3.8.10 (which doesn't involving deleting anything from the schema, so should not cause any rollbacks)
Notes:
Please select the option(s) below …

Bump db client to 3.8.10

---

docker-compose.dev.yml
docker-compose.yml
tests/search/search_fixtures/vespa_test_schema/schemas/document_passage.sd
tests/search/search_fixtures/vespa_test_schema/schemas/family_document.sd

1. Remove obsolete 'version' from docker compose file
2. Remove embeddings from fieldset
Deals with the error:
```
WARNING For schema '...', fieldset 'default': Tensor fields ['...']
cannot be mixed with non-tensor fields ['...'] in the same fieldset.
See https://docs.vespa.ai/en/reference/schema-reference.html#fieldset
```
3. Remove obsolete type assignment for summaries
Deals with the warning for each field:
```
WARNING For schema '...', summary field '...': Specifying the type is
deprecated, ignored and will be an error in Vespa 9. Remove the type
specification to silence this warning.
Visit the [Semver …
```

Deal with some of the many warnings we have when running tests 😬 

---

app/core/ingestion/pipeline.py
pyproject.toml
tests/unit/app/core/test_pipeline.py

Using TDD to fix the db state dropping rows. 
Looking at the test documents that were passing and now the test docs that are failing the difference is the `link_collection_family`: 
Working!
```python
def setup_with_two_docs(db: Session):
"""Creates 2 DFCEs"""
collection1, collection2 = get_default_collections()
add_collections(db, collections=[collection1])
document1, document2 = get_default_documents()
family1, family2 = get_default_families()
family1["documents"] = [document1]
family2["documents"] = [document2]
add_families(db, families=[family1, family2])
link_collection_family(
db,
[
(collection1["import_id"], family1["import_id"]),
(collection1["import_id"], family2["import_id"]),
],
)
```
Failing! 
```python
def setup_docs_with_two_orgs(db: Session):
document1, document2 = …
```

Bugfix for the db-state dropping rows. 

---

.github/workflows/ci-cd.yml
Dockerfile
poetry.lock
pyproject.toml

As part of upgrading all our systems.
Notes:

feat: Migrate to Python `3.10`

---

makefile-local.defs

This was missed in #324.
Notes:

fix: Migrate missed Python version

---

pyproject.toml
tests/search/data_download/test_this_search.py
tests/search/data_download/test_whole_database.py
tests/search/test_vespasearch.py

When working on PDCT-1274, I found that the search test files are huge and kinda grim to maintain. This PR splits the download search tests into separate files as part one of a refactor to make the search tests more maintainable.
Notes:
sure your selected option …

Move search download tests into separate files

---

pyproject.toml
tests/search/test_vespa_ids_search.py
tests/search/test_vespasearch.py

When working on PDCT-1274, I found that the search test files are huge and kinda grim to maintain. This PR splits the vespa IDs search tests into a separate file as part two of a refactor to make the search tests more maintainable.
Notes:
sure your selected …

Move vespa ids search tests into a separate file

---

.env.example
Dockerfile
app/api/api_v1/routers/search.py
app/core/config.py
app/core/search.py
docker-compose.dev.yml
poetry.lock
pyproject.toml
tests/conftest.py
tests/search/vespa/fixtures/vespa_test_schema/services.xml

Updates to the latest version of the sdk which:
- Fixes a bug with filtering
- Moves embedding to vespa so we can delete torch & sentence embeddings
Notes:
Please select …

Bump to latest version of SDK

---

app/api/api_v1/schemas/search.py
app/core/browse.py
app/core/search.py
pyproject.toml
tests/core/test_browse.py
tests/search/test_search.py
tests/search/vespa/setup_search_tests.py
tests/search/vespa/test_vespa_search.py
tests/unit/app/schemas/test_schemas.py

This adds `corpus_import_id` and `corpus_type_name` to the response for search requests.
Notes:
- If you are selecting the version in the …

Add corpus fields to response

---

app/api/api_v1/routers/search.py
pyproject.toml
tests/conftest.py
tests/search/vespa/setup_search_tests.py
tests/search/vespa/test_vespa_corpus_filtering.py

Fix staging - use origin from CORS as custom app configuration token audience value on decode.
Notes:
Please …

Use origin as custom app configuration audience on decode

---

tests/search/vespa/test_vespa_search.py

This test is intended to catch very broken queries, but it is too sensitive and doesnt account for variance caused by other factors (genreal ambient compute fluctuations, etc).
Raising it will unblock others while hopefully also continuing to catch actual breaking changes to queries
Notes:
- If none of these options …

Fix flakey latency test

---

app/db/crud/document.py
pyproject.toml

Make one_or_none a first to workaround multiple geographies until PDCT-1440 is implemented.
Notes:
Please …

Feature/pdct 1553 Make one_or_none a first in document CRUD

---

poetry.lock
pyproject.toml

Bump db client to 3.8.18 to update the DFCE helpers.
Notes:
Please describe the tests that you added to verify …

Bump db client to 3.8.18

---

poetry.lock
pyproject.toml
tests/non_search/routers/lookups/test_config.py
tests/unit/app/core/test_organisation.py

Bump db client to 3.8.22
Notes:

Bump db client to 3.8.22

---

app/service/download.py
pyproject.toml

Reinstate MCF data in data download.
Notes:

Feature/pdct 1644 Reinstate MCF data in data download 

---

app/api/api_v1/routers/search.py
pyproject.toml

Fix check for config filtering
Notes:

Fix search corpora respecting

---

app/api/api_v1/routers/lookups/config.py
app/repository/lookups.py
app/repository/organisation.py
app/service/custom_app.py
pyproject.toml
tests/conftest.py
tests/non_search/routers/lookups/test_config.py
tests/unit/app/core/test_organisation.py

- require an app_token header for the /config endpoint
- validate and decode the app_token in the /config endpoint
- only return stats for organisations linked to allowed corpora from the app_token
Notes:
- Where multiple options are selected, the most …

Config endpoint returns only orgs that correspond to allowed corpora

---

poetry.lock
pyproject.toml
tests/search/vespa/test_vespa_search_pagination.py

Updates the SDK to include a fix for bm25 search on family names and descriptions ([see PR](https://github.com/climatepolicyradar/cpr-sdk/pull/160)).
Also fixes a brittle pagination test.
Notes:
sure your selected option is marked `[x]` with no spaces in between …

fix title and description search

---

pyproject.toml
tests/search/vespa/fixtures/vespa_test_schema/schemas/document_passage.sd
tests/search/vespa/fixtures/vespa_test_schema/schemas/family_document.sd

Update to Vespa schema to fix showing rank features. **This is already deployed on prod Vespa – this just updates the schema of the local test instance**
Notes:
Please …

:robot: bug fix in local vespa schema (summary features)

---

docker-compose.dev.yml
pyproject.toml
tests/search/vespa/fixtures/vespa_test_schema/rules/acronyms.sr

Also changes vespa docker image to point to `latest` - in line with our cloud instances, which auto-update. [See original conversation](https://github.com/climatepolicyradar/cpr-sdk/pull/171#discussion_r1907472789).
Notes:
sure your selected option is marked …

:robot: Update vespa test files - add acronym ruleset

---

poetry.lock
pyproject.toml
tests/search/vespa/test_vespa_search_pagination.py

See https://github.com/climatepolicyradar/cpr-sdk/pull/171.
Note this doesn't enable acronym expansion, but adds a flag in search parameters that can be used to enable it.
**Overall, it looks like we shouldn't enable acronym expansion – the way Vespa does it seems inefficient, and bumps query time from ~0.6 seconds to over 5 seconds when an expansion is done.**
Notes: …

bump sdk to include acronym expansion feature (switched off)

---

poetry.lock
pyproject.toml

[Updates ISO country names and adds VAT](https://github.com/climatepolicyradar/navigator-db-client/releases/tag/v3.9.5)

chore(deps): bump db-client v3.9.5

---

app/main.py
pyproject.toml
tests/conftest.py

- removes the responsibility of the migrations to be exclusively run in `navigator-admin-backend`
Running migrations (write ops) in two places is a risky design.
It also means that backend needs write access which we are trying to avoid. 
Fixes [APP-411: Remove db migrations from navigator-backend](https://linear.app/climate-policy-radar/issue/APP-411/remove-db-migrations-from-navigator-backend)

fix: remove migrations from running on startup

---

pyproject.toml
startup.sh

Without exec - Bash is the parent process, which can cause memory corruption and signal-handling issues.
Using exec makes `python` the top-level process.
Somes docs on this
https://stackoverflow.com/questions/32255814/what-purpose-does-using-exec-in-docker-entrypoint-scripts-serve

fix: use exec to execute python in startup

---

pyproject.toml
startup.sh

- runs `uvicorn` directly as the top-level process
This should allow uvicorn to manage that process and it has better signal handling and a cleaner shutdown.
This is apposed to what we're doing now, which is using python as the top-level process which then runs uvicorn as a sub-process.
> [!NOTE]
> Disclaimer: I am still wrapping my head around pythons contexts, but this is a recommended way [in multiple docs](https://fastapi.tiangolo.com/deployment/manually/) - so I am following that.

fix: run uvicorn as the main process

---

.trunk/trunk.yaml
Dockerfile
pyproject.toml
startup.sh

Adds a whole lot of logging to python, especially around segfaults using
* python debugging
* Gnu Debugger because these are C faults.
This should hopefully help 
Inspiration:
- https://pgrzesik.com/posts/til-python-faulthandler/
- Cursor AI
- ChatGPT
I've removed `checkov` as retrospectively fixing our `Dockerfile`s is not worth the effort at the moment.
I've also removed other trunk.io libs we don't use them and they're causing errors.

feat: log all the python things 🐍🐍🐍

---

app/service/health.py
makefile-docker.defs
pyproject.toml

- uses the [Depends](https://fastapi.tiangolo.com/tutorial/dependencies/#create-a-dependency-or-dependable) on the FastAPI route
- removes it from the method that isn't the FastAPI route as it isn't available at that point
I'll write a test post fix - but want to de-red our deployments.

fix: use Depends on FastAPI route over implementation method

---

app/service/health.py
pyproject.toml
tests/non_search/routers/test_main.py
tests/unit/app/service/test_health.py

- Add healthcheck tests
- Fixed bug in is_rds_online so that we now return False if we can't connect to RDS
Trying to recreate the seg fault issue safely in our test environment at the moment for is_vespa_online, but have not yet managed. Will do this separately.
Notes:
- If you are selecting the version in the list above using the …

Add tests for healthchecks

---

app/models/search.py
app/service/search.py
pyproject.toml
tests/search/test_search.py

https://www.notion.so/climatepolicyradar/Brief-Give-users-option-to-change-ordering-of-matches-on-document-viewer-and-change-default-back-t-1e59109609a480738f3bfaa6c0f23939
Notes:
brackets …

Add page num ordering as option rather than default

---

.github/workflows/merge-to-main.yml
api/infra/__main__.py
families-api/justfile
pyproject.toml

- adds `staging` deploy on merge-to-main for `families-api`
- adds "[reviewed deployment](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/reviewing-deployments)" deploy to `production` AKA `latest`
- releases a hashed deploy to github SHA
- is on the [`production` environment](https://github.com/climatepolicyradar/navigator-backend/settings/environments/6731733887/edit)
- GitHub protection are all-or-nothing, so any other action wanting to use the production `environment` will be protected
- A mitigation for the above is creating another environment called `production-protected` or similar
- It current requires @climatepolicyradar/tech-devs to review the deploy. While I can see this being a risk when wanting to deploy in urgency (and this is …

`families-api` deploy

---

poetry.lock
pyproject.toml
tests/non_search/routers/geographies/setup_world_map_helpers.py
tests/non_search/routers/lookups/test_config.py
tests/non_search/setup_helpers.py
tests/unit/fixtures/CCLW.document.i00000002.n0000.json
tests/unit/fixtures/CCLW.document.i00000006.n0000.json
tests/unit/fixtures/CCLW.document.i00000008.n0000.json
tests/unit/fixtures/CCLW.document.i00000016.n0000.json
tests/unit/fixtures/CCLW.document.i00000018.n0000.json
tests/unit/fixtures/CCLW.document.i00000026.n0000.json
tests/unit/fixtures/CCLW.document.i00000030.n0000.json
tests/unit/fixtures/CCLW.document.i00000038.n0000.json
tests/unit/fixtures/CCLW.document.i00000040.n0000.json
tests/unit/fixtures/CCLW.document.i00000058.n0000.json
tests/unit/fixtures/CCLW.document.i00000066.n0000.json
tests/unit/fixtures/CCLW.document.i00000067.n0000.json
tests/unit/fixtures/CCLW.document.i00000144.n0000.json
tests/unit/fixtures/CCLW.document.i00000153.n0000.json
tests/unit/fixtures/CCLW.document.i00000192.n0000.json
tests/unit/fixtures/CCLW.document.i00000204.n0000.json
tests/unit/fixtures/CCLW.document.i00000214.n0000.json
tests/unit/fixtures/CCLW.document.i00000222.n0000.json
tests/unit/fixtures/CCLW.document.i00000247.n0000.json
tests/unit/fixtures/CCLW.document.i00000280.n0000.json
tests/unit/fixtures/CCLW.document.i00000287.n0000.json
tests/unit/fixtures/CCLW.document.i00000290.n0000.json
tests/unit/fixtures/CCLW.document.i00000291.n0000.json
tests/unit/fixtures/CCLW.document.i00000298.n0000.json
tests/unit/fixtures/CCLW.document.i00000305.n0000.json

- bump db_client to latest (3.9.10 -> 3.9.12)
Notes:
Please describe the tests that you added to verify your …

Update db_client to latest

---

api/infra/__main__.py

Makes concepts deployable to `production`

fix: make bucket stack specific for deploy permissions

---

geographies-api/Dockerfile
geographies-api/docker-compose.yml
geographies-api/infra/Pulumi.production.yaml
geographies-api/infra/Pulumi.staging.yaml
geographies-api/infra/__main__.py

- we have decided to spike using a cdn to store the geographies data in an s3 bucket, as such we are updating the infrastructure code to allow us to do so whilst we are spiking
Notes:
- Where multiple options are selected, the most senior option ticked …

refactor: update geo infra to allow us to push documents to s3 bucket

---

families-api/app/main.py
families-api/app/test_main.py

- fetches and renders concepts in the response
Test case is caught via the 200 response test.
```json
{
"data": {
"import_id": "Sabin.family.75886.0",
"title": "Bowfin Keycon Holdings, LLC v. Pennsylvania Department of Environmental Protection",
"description": "Challenge to Pennsylvania regulations implementing participation in the Regional Greenhouse Gas Initiative.",
"concepts": [
{
"id": "Pa.",
"ids": [],
"type": "legal_entity",
"relation": "jurisdiction",
"preferred_label": "Pa.",
"subconcept_of_labels": []
}
],
"corpus": {
"organisation_id": 11,
"import_id": "Academic.corpus.Litigation.n0000",
"title": "Litigation"
},
"organisation": "Sabin",
"summary": "Challenge to Pennsylvania regulations implementing participation in the Regional Greenhouse Gas Initiative."
}
}
```

Add concepts to family

---

api/infra/__main__.py
api/uv.lock

We were missing CORS policies for our API endpoints, which was causing errors in the frontend. This resolves that and also adds a missing uv.lock file for the infra

Feature/app 803 propagate CORS policy change for microservices

---

api/infra/__main__.py

- Allows the `ORIGIN` header to act as part of the cache key
this is because the endpoint if being cached with the `access-control-allow-origin` value of whatever app hits it first.
e.g.
- cpr app hits options endpoint
- endpoint is cached with `access-control-allow-origin: cpr.climatepolicyradar.org`
- cclw hits it
- cache returns `access-control-allow-origin: cpr.climatepolicyradar.org`
- does not work
This allows the cache to VARY on ORIGIN.
This does mean all we vary on all ORIGN requests which then hit origin, which is not great - [tech debt tracked here](https://linear.app/climate-policy-radar/issue/APP-805/find-a-way-to-cache-options-method-on-apienv).
Fixes https://linear.app/climate-policy-radar/issue/APP-807/cors-issues-on-cclwmcf-when-hitting-new-microservice-endpoints

fix: allow ORIGIN header as part of the cache key

---

concepts-api/create_duckdb.py

- removes fallback for concepts data about classifiers
- changes `List` => `list`
Fixes: https://linear.app/climate-policy-radar/issue/APP-618/remove-fallback-for-concepts-with-classifiers-to-avoid-confusion

fix: remove concepts data fallback

---

concepts-api/create_duckdb.py
concepts-api/justfile

Uses `ENV` to calculate which [classifiers_spec](https://github.com/climatepolicyradar/knowledge-graph/tree/main/flows/classifier_specs) file to use.
[This is based on env var we use for oTel](https://github.com/climatepolicyradar/navigator-backend/blob/dfd32c2da4157cf8e61341a22d781d688f7bd14f/concepts-api/app/main.py#L24)
Fixes https://linear.app/climate-policy-radar/issue/APP-617/use-correct-env-file-from-concepts-store-to-get-concepts-with

fix: using ENV to create_duckdb for classifiers_spec file

---

README.md

Adds uv workspaces docs to the README
Fixes https://linear.app/climate-policy-radar/issue/APP-799/update-root-readme-to-describe-how-the-monorepo-works

docs: add uv workspaces info to README

---

.github/workflows/ci-cd.yml
backend-api/uv.lock
concepts-api/README.md

- upgrade fully to python 3.12
We might want to investigate using [`.python-version`](https://docs.astral.sh/uv/concepts/python-versions/#python-version-files) - but don't want to create more work for myself.
Fixes https://linear.app/climate-policy-radar/issue/APP-594/update-python-version-in-nav-back

fix: move completely to python 3.12

---

api/infra/__main__.py
concepts-api/infra/__main__.py
families-api/infra/__main__.py
geographies-api/infra/__main__.py

Instead of using raw JSON to define the infrastructure in this repo, use the pulumi AWS library.
Why?
- Clearer parameter names and types instead of guessing JSON structure
- Self-documenting code with explicit parameter names
- Easier to refactor and maintain the infrastructure
- More type safe
I've validated by doing a pulumi up -r (to refresh) for each stack that this PR introduces no new changes and leaves the existing pulumi states unchanged.

Use pulumi library to define infra

---

families-api/docker-compose-admin-backend.yml

Adds a compose file that allows us to connect to the admin-backend DB. (Or any other).
There might be better ways to do this going forward, but it allows us to all have a way to e2e when testing `litigation-data-mapper -- JSON --> bulk-import --> navigator-admin-backend --> families-api`.
This helps the DevX as we want to get all our data woes sorted before running a full reindex.
- navigator-admin-backend
- `make dev`
- add 👇 into the DB to be used by the bulk-import
- `insert into APP_USER(email, name, hashed_password, is_superuser) values ('user@navigator.com', 'TestUser', '$2b$12$hvxOvIgoGs35GQY/53ULIuTzLFJJ7BVxeD8e.mBPktQwZ0NZwp9iq', true);`
- `insert into organisation_admin values ('user@navigator.com', 1, 'Tester', true, true);`
- navigator-backend:
- from root or repo  
- `docker …

fix: add compose file to test against admin-backend

---

backend-api/app/models/search.py
backend-api/app/repository/lookups.py
backend-api/app/service/search.py
backend-api/tests/search/test_search.py
geographies-api/app/main.py
geographies-api/app/router.py

We are updating our vespa query; adding subdivisions to the geography query. 
A subdivision in our code base is effectively a geography, so have updated the countries array that takes all the iso codes and passes them to vespa [see line 387].
Have added a function to validate the iso codes based on the objects in our geo database. Made the decision to use the db to validate the iso codes rather than the geo service endpoint as was concerned network latency might affect search performance.
Wonder if it is worth changing that array name from `countries` to `geographies`

feat: add subdivisions to geography filter query

---

backend-api/app/repository/lookups.py
backend-api/app/service/search.py
backend-api/tests/search/test_search.py

When sending geographies filters to vespa we want to ensure that we do not include parent iso codes as well as subdivisions as this does not filter through the results as we intend it to and returns families tagged with the parent iso codes as well as the subdivisions, which makes the filter redundant. 

refactor: we do not want to send parent country slug when passing

---

families-api/app/main.py
families-api/app/test_main.py

- adds events to `FamilyDocument` response
Towards https://linear.app/climate-policy-radar/issue/APP-816/render-family-page-via-the-new-families-api-for-new-family-page
For this https://api.climatepolicyradar.org/families/Sabin.family.92131.0
```json
{
"documents": [
{
"import_id": "Sabin.document.92131.92132",
"variant": "Original Language",
"slug": "lawsuit-sought-to-compel-updating-of-development-and-production-plans-prior-to-resumption-of-oil-and-gas-activities_4767",
"title": "Lawsuit Sought to Compel Updating of Development and Production Plans Prior to Resumption of Oil and Gas Activities",
"md5_sum": "51f6cb7684518f508332c39bbf547cdf",
"cdn_object": "https://cdn.climatepolicyradar.org/USA/2025/center-for-biological-diversity-v-burgum_51f6cb7684518f508332c39bbf547cdf.pdf", …
```

feat: add events to familes response

---

families-api/app/main.py

- adds `import_id` to FamilyEventPublic to be used by the frontend.
Everything in my head wants to use `id` - but to avoid transformation fatigue, I have stuck with this as we use it elsewhere.
CC: @jesskelsall

fix: add import_id to FamilyEventPublic

---

families-api/app/main.py

- returns `FamilyPublic` from the `/families` endpoint
- uses the `ClassBase/Class/ClassPublic` format ([as per the SQLModel docs](https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/#docs-ui-with-hero-responses)) for Corpus[^1]
- returns the `organisation` as part of the `corpus` property e.g.
```json
{
"corpus": {
"import_id": "MCF.corpus.AF.n0000",
"title": "Adaptation Fund Projects",
"corpus_type_name": "AF",
"organisation": {
"name": "AF",
"id": 7,
"attribution_url": null
}
}
}
```  
[^1]: I am going to standardise around this model in follow up PRs with docs

fix: return families from families / endpoint

---

families-api/app/main.py

- adds `FamilyDocumentPublicWithFamily` to be used on the `families/documents`
- this differs `FamilyDocumentPublic` as we don't want to return families on the families endpoint, creating a self referential problem

fix: add family to familydocument

---

families-api/app/main.py

this model gives us more properties on the document object
Before
After

feat: use famdoc public as base for document response

---

families-api/app/main.py

We were missing `bucket` prefix from the cdn object which meant that the url was broken 
This works : 
https://cdn.climatepolicyradar.org/navigator/USA/2025/environmental-defense-fund-v-epa_ac6863a762177b969a6e4d708b2882bb.pdf
Whereas this doesnt
https://cdn.climatepolicyradar.org/USA/2025/environmental-defense-fund-v-epa_ac6863a762177b969a6e4d708b2882bb.pdf

add navigator bucket title in cdn object so that it can be accessed

---

families-api/app/main.py

- Adds the `page` param to list endpoints in order to be able to get all the results
This is based on my use case that i want to be able to get all families to do some analysis on them

feat: add limit to families API endpoints

---

families-api/app/main.py

per title return empty string if document role does not exist on metadata, follows what we have done in the [backend api ](https://github.com/climatepolicyradar/navigator-backend/blob/b9aba42e4e2099097c219b9ff0a0f7061123db11/backend-api/app/repository/document.py#L160) and ensures that the frontend does not break. 

fix: return empty string if document role does not exist on metadata

---

families-api/app/main.py

Fix `self.valid_metadata.get("role", [None])[0]` would still return the first element of the `[None]` list if there was valid metadata and role was not a property on that dict. We just want to return an empty string in all instances where document role does not exist

fix: we do not want to return none for document role

---

families-api/app/router.py
families-api/tests/test_main.py

Implements an `OR` query for `corpus.import_id` on the `read_families` endpoint.
This will allow us to then cross reference whether we have families for certain `geos` on the frontend once we have implemented to `geos` filter.
In short the filters will work like
```
corpus.import_id=1&corpus.import_id=2&geography.id=US-CAL&geography.id=AUS
(corpus.import_id=1 OR corpus.import_id=2) AND (geography.id=USA OR geography=US-CAL OR geography.id=AUS)
```
Which could be broken down into and run in this order
- all filters with the same name are joined with `OR`
- all ☝️ filters are joined by `AND`
This will get us all the way we need to for litigation.
---
@annaCPR and I had a great discussion around designing our filters and thought there is more we could do - but this would be the simplest and …

feat: corpus.import_id filter on read_families

---

families-api/app/models.py
families-api/tests/test_main.py

Adds `CorpusType` to the `/families` response and tests.
The tests on the `test_read_family_200` validates this as it does a `model_validate`.
```json
{
"import_id": "CCLW.family.10882.0",
"title": "Minister of Industry Decree No. 27/2020 on Specifications, Development of Roadmaps, and Provisions to Calculate the Domestic Component Standards for Domestic Battery Electric Vehicles (BEV)",
"concepts": [],
"corpus": {
"import_id": "CCLW.corpus.i00000001.n0000",
"title": "CCLW national policies",
"corpus_type_name": "Laws and Policies",
"organisation": {
"name": "CCLW",
"id": 1,
"attribution_url": null
},
"corpus_type": {
"name": "Laws and Policies",
"description": "Laws and policies"
}
}
}
```

feat: add corpus_type to families response

---

backend-api/app/api/api_v1/routers/families.py
backend-api/app/models/search.py
backend-api/tests/non_search/routers/families/test_latest_published.py

Only send values that we need for the frontend component.
As a drive by add a limit to the request endpoint.
Limit
No limit - default of 5

refactor: strip down the response endpoint

---

families-api/app/router.py
families-api/tests/test_main.py

- adds ordering to the families endpoint as we use `LIMIT` which can lead to unpredictable results
> When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. You might be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? The ordering is unknown, unless you specified ORDER BY.
-- [postgres docs](https://www.postgresql.org/docs/current/queries-limit.html)
[This was discovered while paginating through the API looking for deletions](https://github.com/climatepolicyradar/litigation-data-mapper/pull/93).

fix: add tests for family ordering

---

families-api/app/models.py

- reader `attribution_url` to corpus 
[This was added to the table via the db client here](https://github.com/climatepolicyradar/navigator-db-client/pull/104).
https://linear.app/climate-policy-radar/issue/APP-1259/add-attribution-url-to-families-api

fix: add attribution URL to corpus
