poetry.lock
pyproject.toml

Bug found in production - see discussion on slack here: https://climate-policy-radar.slack.com/archives/C04CR0B3KD4/p1674724615493809?thread_ts=1674718871.901429&cid=C04CR0B3KD4
- https://stackoverflow.com/a/72677699
- https://github.com/encode/starlette/discussions/1527#discussioncomment-2234702
This can be fixed updating to the latest versions of:
- https://github.com/tiangolo/fastapi
- https://github.com/encode/uvicorn
- https://github.com/encode/starlette

BUGFIX: Update fastapi, starlette and uvicorn packages

---

app/data_migrations/__init__.py
app/data_migrations/populate_taxonomy.py
app/initial_data.py

The first of several PRs to populate and use the taxonomy on ingestion.

BAK-1305 Create and populate metadata_taxonomy

---

alembic/versions/0013_families_and_collections.py
app/db/models/law_policy/__init__.py
app/db/models/law_policy/family.py
scripts/ingest_dfc/dfc/collection.py
scripts/ingest_dfc/dfc/family.py
scripts/ingest_dfc/dfc/metadata.py
scripts/ingest_dfc/dfc/processor.py
scripts/ingest_dfc/utils.py

BAK-1305: Add & Validate Metadata

---

.pre-commit-config.yaml
app/db/crud/document.py
poetry.lock
pyproject.toml
tests/core/db/test_crud.py
tests/routes/test_document_relationships.py
tests/routes/test_documents.py

Mostly matching/reflecting the new pre-commit config in the dev dependencies in pyproject.toml

Complete updates for linting/checking

---

app/api/api_v1/routers/admin.py
app/core/ingestion/collection.py
app/core/ingestion/family.py
app/core/ingestion/ingest_row.py
app/core/ingestion/match.py
app/core/ingestion/metadata.py
app/core/ingestion/organisation.py
app/core/ingestion/physical_document.py
app/core/ingestion/processor.py
app/core/ingestion/reader.py
app/core/ingestion/utils.py
app/core/ingestion/validator.py
app/db/models/law_policy/collection.py

This PR is solely for the first stage - getting the scripting code into `main`

Add ingestion script into backend code

---

app/api/api_v1/routers/summaries.py
app/api/api_v1/schemas/search.py
app/core/browse.py
app/core/search.py
tests/conftest.py
tests/routes/test_data_fixtures.py
tests/routes/test_geography_summaries.py
tests/routes/test_summaries_country.py

Adds support for document/family/collection database schema to geography summary.
Still a WIP, but route tests are in the process of being modified.

Family support for geography summary

---

app/api/api_v1/routers/admin.py
app/api/api_v1/routers/unauthenticated.py
app/core/ratelimit.py
app/db/crud/document.py
tests/routes/test_unauthenticated.py

Make rate limit configurable

---

app/core/ingestion/processor.py
app/db/crud/document.py
tests/routes/test_documents.py

Debugging bug (PR to trigger actions)

---

app/core/ratelimit.py

Up the rate limit x10

---

app/core/search.py
app/db/crud/document.py
tests/routes/test_search.py

- Found where the issue is - and written a failing test
- FIXED

Identify where the issue lies

---

app/api/api_v1/routers/admin.py
app/api/api_v1/routers/auth.py
app/api/api_v1/routers/documents.py
app/api/api_v1/routers/lookups/config.py
app/api/api_v1/routers/lookups/geo_stats.py
app/api/api_v1/routers/search.py
app/api/api_v1/routers/summaries.py
app/api/api_v1/routers/unauthenticated.py

All endpoints should now be decorated with ` @limiter.exempt`

Disable rate limiting on all endpoints

---

app/api/api_v1/routers/admin.py
app/api/api_v1/routers/auth.py
app/api/api_v1/routers/documents.py
app/api/api_v1/routers/lookups/config.py
app/api/api_v1/routers/lookups/geo_stats.py
app/api/api_v1/routers/search.py
app/api/api_v1/routers/summaries.py
app/api/api_v1/routers/unauthenticated.py

This reverts commit 621825f484db78506c20fd12a7efd8026f445922.

Revert "Disable rate limiting on all endpoints (#55)"

---

app/api/api_v1/routers/search.py
app/core/browse.py
app/core/search.py
app/db/crud/deprecated_document.py
app/db/crud/document.py
tests/routes/test_config.py
tests/routes/test_documents_deprecated.py
tests/routes/test_search.py

This PR attempts to:
- improve search performance issues by reducing the amount of work done by every grouped search request.
- completes browse filtering functionality
- improves test feature coverage
Existing search tests should be adequate. Verification of caching behaviour will be added.

Search & Browse fixes/enhancements

---

app/api/api_v1/routers/admin.py
app/api/api_v1/schemas/document.py
app/core/validate.py
tests/routes/test_admin.py

Validating that all the climate laws urls have documents stored in s3. 

---

app/api/api_v1/routers/admin.py
app/api/api_v1/schemas/document.py
app/db/crud/document.py
tests/routes/test_documents.py

- Reduce size of one-line comments to pass ruff
- remove "slugs" as a list and replace with "slug" as a string
- update tests

Only return single slug

---

app/core/browse.py
app/db/models/law_policy/family.py

Improve browse performance by removing >3000 separate queries

---

app/core/search.py
app/db/crud/document.py

Fix a number of bugs in family creation from search results

Fix a number of bugs in family creation from search results

---

app/core/ingestion/collection.py
app/core/ingestion/family.py
app/core/ingestion/physical_document.py
app/core/ingestion/processor.py
app/core/ingestion/utils.py
app/db/models/law_policy/family.py
tests/core/ingestion/helpers.py
tests/core/ingestion/test_collection.py
tests/core/ingestion/test_event.py
tests/core/ingestion/test_family.py
tests/core/ingestion/test_ingest_row.py
tests/core/ingestion/test_metadata.py
tests/core/ingestion/test_physical_document.py
tests/core/ingestion/test_validate_row.py
tests/routes/document_helpers.py
tests/routes/test_documents.py

- Refactor tests
- Remove migrate functionality from old schema
- Adds creating new doc/fam/cols
- Adds updating doc/fam/cols
- Adds lots more tests
NOTE: Updates implemented:
```
```

Ingest creates/updates documents

---

app/core/search.py

Fixes a small bug in an as-yet unused code path.

Fix opensearch index list generation

---

app/api/api_v1/schemas/search.py
app/core/browse.py
app/core/ingestion/ingest_row.py
app/core/search.py
app/db/crud/document.py
tests/core/ingestion/helpers.py
tests/core/ingestion/test_event.py

This PR adds last_updated_date to search results.
Extended tests.

Add last updated date to search results

---

app/core/validation/util.py
tests/core/ingestion/test_pipeline.py
tests/core/validation/test_util.py

Update filename for documents written into S3 to trigger a pipeline run.

Change trigger filename for pipeline

---

app/core/search.py
tests/routes/test_search.py

Fix handling of languages in CSV download (previously caused internal server error).
Enhanced test setup to include language support in search tests & extend CSV content tests to include language.

Fix handling of languages in search result CSV download

---

app/api/api_v1/schemas/search.py
app/core/browse.py
app/core/ingestion/ingest_row.py
app/core/search.py
tests/routes/test_search.py

Resolve FIXMEs
Tests unchanged or extended where required.

Resolve FIXMEs

---

app/api/api_v1/routers/unfccc_ingest.py
app/core/ingestion/collection.py
app/core/ingestion/processor.py
app/core/ingestion/unfccc/ingest_row_unfccc.py
app/core/ingestion/validator.py
app/data_migrations/data/unf3c/submission_type_data.json
tests/core/ingestion/test_unfccc_ingest_row.py
tests/routes/test_admin_unfccc.py

Locally this is fixing all the errors apart from the multiple-collections issue.

Fix missing/extra UNFCCC columns

---

app/api/api_v1/routers/unfccc_ingest.py

- Ensure the results are logged out
- fix bug when writing db state with CCLW and UNFCCC docs in

Fix no results logged

---

tests/core/ingestion/test_unfccc_ingest_row.py

Removed the deprecated use of `query.get`

Removed the deprecated use of `query.get`

---

app/api/api_v1/routers/admin.py
app/api/api_v1/routers/cclw_ingest.py
app/api/api_v1/routers/unfccc_ingest.py
app/api/api_v1/schemas/document.py
app/core/validation/__init__.py
tests/routes/document_helpers.py
tests/routes/test_document_families.py

Add a test for the import_ids

---

app/core/ingestion/processor.py
tests/routes/test_admin_unfccc.py

Summaries now built on the fly - modified test

SOF-51 Dynamically create summary for UNFCCC

---

app/core/ingestion/unfccc/event.py

Fixes the fixed title to be that of the type - like the CCLW ones

Create the UNFCCC event with a title of the event type

---

app/core/ingestion/family.py
tests/routes/test_document_families.py
tests/routes/test_search.py

SOF-49 fall out ... this does 2 main things:
- Create families on ingest in PUBLISHED state, and
- Adds tests for searches and makes comments on actual vs expected behaviour

Create families on ingest in PUBLISHED state

---

scripts/validate_cclw_sheet/download.py

Now daily validates the retool sheet https://docs.google.com/spreadsheets/d/10xcBKgiYoT7eWQoyoWYlELO_z7TC1XE-_CIkC0vONWk/edit#gid=1610069741 

Update the daily validation to point at the retool sheet

---

.github/workflows/daily.yml
scripts/validate_cclw_sheet/validate-ingest.sh

Makes some of the data more visible as it goes through the process

Daily Validation: add some more debug and upate the script

---

app/core/validation/__init__.py
tests/core/validation/test_util.py

More useful import_id validation
Additional validation tests

Update import_id match to be less restrictive, but better validated

---

Dockerfile
app/core/search.py
tests/routes/test_search.py

Update CSV download generation to use whatever metadata fields are discovered from the result documents.
Existing tests have been extended & data loading extended to generate taxonomy data for tests.

Dynamically generated CSV download metadata columns

---

app/core/ingestion/collection.py
app/core/ingestion/processor.py
tests/core/ingestion/test_collection.py

- Tests that the collection name and description can be changed
- Adds the ability to change a family's collection (enforces one per family for CCLW)
- Adds test for the above

PDCT-167 CCLW Support Amending Collections

---

app/core/ingestion/collection.py
app/core/ingestion/processor.py
tests/core/ingestion/test_collection.py

Adds test and functionality of remove a family from a collection if it is blanked

PDCT 167/update collections allow for collection removal

---

scripts/validate_cclw_sheet/download.py

Daily validation failing as we're not downloading all the sheet.
TEST RUN HERE: https://github.com/climatepolicyradar/navigator-backend/actions/runs/5477655511

Download entire sheet

---

app/core/search.py

We suspect that embeddings generation may be taking longer than expected. This PR explicitly instruments the calls to generate sentence embeddings so we can verify.
N/A

Explicitly instrument embeddings generation

---

.github/workflows/ci.yml
.github/workflows/semver.yml

update configure-aws-credentials to latest

---

README.md

fix: documentation links in readme

---

startup.sh

Fix regression in cert file generation

---

app/db/models/law_policy/family.py

Added hybrid expression for family status hybrid property in backend DB model for Family entity in keeping with [this PR](https://github.com/climatepolicyradar/navigator-admin-backend/pull/50/files).

Add hybrid expression for family status in db model.

---

app/data_migrations/data/unf3c/submission_type_data.json
tests/routes/test_config.py

Added Industry Report submission type for OEP docs (hack ingest).

Added Industry Report as submission type

---

app/api/api_v1/routers/search.py

Initial feedback for api users when running a query with an invalid query string. The query error has more details so we could send that back in the future too if we decide it is a good idea to share it.
This builds on work in the data access library: https://github.com/climatepolicyradar/data-access/pull/102 The version of the data access library needs updating here after that is deployed.
To Do
There are no vespa tests to build on, we need to come back and add some. It is a low risk change though as vespa is not live yet

Feature/pdct 614 handle vespa errors gracefully (Part Two)

---

app/api/api_v1/routers/search.py
app/core/download.py

Replaced redirect to data dump file on its own with redirect to compressed archive containing README and data dump.

PDCT-796 Create archive  containing README and data dump CSV.

---

app/db/crud/document.py

Remove class DocumentExtraCache as its no longer used.

---

app/api/api_v1/schemas/metadata.py
app/core/lookups.py
app/core/organisation.py
tests/routes/test_config.py

Adds a breakdown of CCLW stats for use on the homepage 
See PDCT-553

Add CCLW stats to the config endpoint

---

Dockerfile
app/api/api_v1/routers/geographies.py
app/api/api_v1/schemas/geography.py
app/main.py

Add skeleton for `/geographies` endpoint in the nav-backend to be used by the world map.

Pdct 885/add api endpoint for returning all of the geographies and their stats

---

tests/routes/dfce_helpers.py
tests/routes/setup_helpers.py
tests/routes/test_document_families.py

Restore tests for metadata on documents endpoint

---

tests/conftest.py
tests/routes/test_document_families.py

Speeds the tests up by wrapping each test in a transaction
Notes:
Please describe the tests that you added to …

Speed up data_db - uses transaction around tests

---

app/api/api_v1/routers/search.py
app/api/api_v1/schemas/search.py
app/main.py
pyproject.toml

This documentation is limited to the search endpoint for now, as it is the most used. At the time of this commit it is not possible to make the `search_in_schema` default to false. But this might be a neater way of doing it in the future, see: https://github.com/tiangolo/fastapi/discussions/9226
This work also clashes with some deprioritised work to move these models to the sdk. That work is intended to simplify the code and make the experience for data scientists more consistent with search users. However, other urgent work meant it was left with some fields defined in both. See: https://linear.app/climate-policy-radar/issue/PDCT-1024/parameter-handling-needs-deduplicating-response Not really a problem but does leave this a little messier then the ideal.
Adding to that ticket to move the …

Add initial documentation for search endpoint

---

app/api/api_v1/schemas/search.py
poetry.lock
pyproject.toml
tests/search/test_limit_alias.py
tests/search/test_search.py
tests/search/test_vespasearch.py

We want to change the api to use `page_size` instead of `limit`, so that
limit can be adjusted and can be used consistently across the backend and
vespa. Step one of doing this is aliasing `limit` with `page_size` so
we can change the frontend over and then return to change the backend.
This means we can make the change without downtime.
Also adds temporary tests confirming limit alias works. These ensure the limit
& page_size are interchangeable. The plan would be to remove these tests again
after changing the frontend.
difference between `MAJOR`, `MINOR`, and …

Alias `limit` to `page_size` so we can swap them

---

poetry.lock
pyproject.toml

Notes:
sure your selected option is marked `[x]` with no spaces …

Bump db-client to fix constraint

---

.github/dependabot.yml
poetry.lock
pyproject.toml

This PR integrates a dependabot config file to automate the upgrade of dependencies. 
This has been integrated into a number of repositories.

Adding a dependabot config file.

---

.github/dependabot.yml

Ignore db_client when doing dependency updates [PDCT-1232](https://linear.app/climate-policy-radar/issue/PDCT-1232/automate-dependency-updates-for-navigator-backend)
The db client versioning needs to be closely controlled at the moment as not every new release of the db client is always ready to propagate through into both the nav backend and admin backend at the same time (one release might remove the references in the admin service as we want to check things still work before propagating through to the nav backend for example).
Because of this, we want to force Dependabot to ignore the db_client package so we can manually control this. The db client isn't published to PyPi, just GitHub.
@THOR300 is the point of reference for dependabot - so we need a review from him before we merge. …

Ignore db_client when doing dependency updates

---

poetry.lock
pyproject.toml

Update the dependencies to include pytorch for arm 
Notes:
sure …

add torch to dependencies for arm

---

docs/custom_apps.md

Add disclaimer to use secret key that corresponds to the AWS environment you want to generate the token for.
Notes:
Please select the option(s) below that are most …

Add secret key disclaimer to docs

---

docker-compose.dev.yml
tests/search/search_fixtures/vespa_family_document.json
tests/search/search_fixtures/vespa_test_schema/schemas/family_document.sd

This updates the schema for our test instance of vespa. This is used for tests in CI, so tests passing here gives us confidence in the changes we are making to our live instances. See: 
- https://github.com/climatepolicyradar/navigator-infra/pull/684
- https://github.com/climatepolicyradar/navigator-infra/pull/686
Notes:
- If you are …

Update test vespa with new schema

---

poetry.lock
pyproject.toml

Bumps db-client version
Notes:

Bump db-client version

---

app/api/api_v1/schemas/document.py
app/core/download.py
poetry.lock
pyproject.toml
tests/non_search/setup_helpers.py

The sdk & backend both had the same identical model. This makes changes more convoluted and runs the risk of growing divergence over time. Here we consolidate them to use the sdk version instead, meaning that new fields can be managed in one place.
Note that there was the small config difference already which I have preserved by inheriting the sdk model into the existing backend model. I wanted to minimise how much I was changing all in one go but we can take this further in the future if we would like to.
See [all sdk changes](https://github.com/climatepolicyradar/cpr-sdk/compare/v1.1.9...v1.3.11) that are introduced here. (Essentially various version bumps + the model changes). And the [code for the sdk model](https://github.com/climatepolicyradar/cpr-sdk/blob/main/src/cpr_sdk/pipeline_g …

Use sdk model for pipeline input

---

.github/pull_request_template.md

- updates PR template to include a check that the db_client is on the latest version
- 
Notes:
- If you are selecting the version in the list …

Update PR template to include checking the db_client version is latest

---

app/core/ingestion/pipeline.py
pyproject.toml
tests/unit/app/core/test_pipeline.py

This Pull Request: 
---
- Temporarily replaces a ValueError with a logger statement as we expect to hit this during the backfill. We are accepting the risk of low data integrity from the json produced and will in the near future integrate a fix. 
Notes:
sure …

Updating to not throw value error.

---

tests/core/test_browse.py
tests/non_search/app/documents/test_get_document_families.py
tests/non_search/setup_helpers.py
tests/unit/app/core/test_pipeline.py
tests/unit/conftest.py
tests/unit/fixtures/CCLW.document.i00000002.n0000.json
tests/unit/fixtures/CCLW.document.i00000006.n0000.json
tests/unit/fixtures/CCLW.document.i00000008.n0000.json
tests/unit/fixtures/CCLW.document.i00000016.n0000.json
tests/unit/fixtures/CCLW.document.i00000018.n0000.json
tests/unit/fixtures/CCLW.document.i00000026.n0000.json
tests/unit/fixtures/CCLW.document.i00000030.n0000.json
tests/unit/fixtures/CCLW.document.i00000038.n0000.json
tests/unit/fixtures/CCLW.document.i00000040.n0000.json
tests/unit/fixtures/CCLW.document.i00000058.n0000.json
tests/unit/fixtures/CCLW.document.i00000066.n0000.json
tests/unit/fixtures/CCLW.document.i00000067.n0000.json
tests/unit/fixtures/CCLW.document.i00000144.n0000.json
tests/unit/fixtures/CCLW.document.i00000153.n0000.json
tests/unit/fixtures/CCLW.document.i00000192.n0000.json
tests/unit/fixtures/CCLW.document.i00000204.n0000.json
tests/unit/fixtures/CCLW.document.i00000214.n0000.json
tests/unit/fixtures/CCLW.document.i00000222.n0000.json
tests/unit/fixtures/CCLW.document.i00000247.n0000.json
tests/unit/fixtures/CCLW.document.i00000280.n0000.json
tests/unit/fixtures/CCLW.document.i00000287.n0000.json
tests/unit/fixtures/CCLW.document.i00000290.n0000.json
tests/unit/fixtures/CCLW.document.i00000291.n0000.json
tests/unit/fixtures/CCLW.document.i00000298.n0000.json
tests/unit/fixtures/CCLW.document.i00000305.n0000.json

This is to help us catch more bugs, as we missed 1 recently.
CLOSES PLA-151
Notes:
Please describe the tests …

test: Add more scenarios for the pipeline trigger

---

app/core/config.py
poetry.lock
pyproject.toml

- Bump CPR SDK to 1.4.4
Notes:

Bump CPR SDK to 1.4.4

---

tests/search/vespa/fixtures/vespa_test_schema/search/query-profiles/default.xml

Notes:
sure your selected option is marked `[x]` with no spaces …

:robot: Update vespa test files

---

scripts/db_state_validator_click.py

Updating to use sdk declared types. 
Notes:

Updating the script to use sdk models.

---

app/models/search.py
app/repository/sql/download.sql
app/repository/sql/pipeline.sql
docs/api/search.md
poetry.lock
pyproject.toml
tests/search/test_search.py
tests/search/vespa/setup_search_tests.py

Removed Passed/Approved hardcoded logic to replace with checking for equality with new datetime_event_name
Notes:
Please select the option(s) below that are most …

Feature/pdct 1514 replace passed/approved from backend

---

docs/local_full_stack_setup/README.md
pyproject.toml

Updating the documentation for the local setup to include details on how to load rds from an sql dump. 
Notes: …

Updating the local setup documentation.

---

app/api/api_v1/routers/summaries.py
app/models/search.py
app/repository/search.py
pyproject.toml
tests/non_search/routers/summaries/test_geography_summaries.py

Lockdown geography page route
Notes:

Lockdown geography page route

---

app/api/api_v1/routers/search.py
app/service/health.py
app/service/search.py
pyproject.toml
tests/search/vespa/test_range_and_keyword_filters_search.py
tests/search/vespa/test_this_vespa_search_download.py
tests/search/vespa/test_vespa_concept_filters.py
tests/search/vespa/test_vespa_corpus_filtering.py
tests/search/vespa/test_vespa_ids_search.py
tests/search/vespa/test_vespa_metadata_filters_search.py
tests/search/vespa/test_vespa_query_ignores.py
tests/search/vespa/test_vespa_search.py
tests/search/vespa/test_vespa_search_pagination.py
tests/search/vespa/test_vespa_search_result_order.py
tests/search/vespa/test_whole_database_download.py

Refactor search router into service layer
Notes:
Please describe the tests that you added to verify your …

Refactor search router into service layer

---

app/service/search.py
pyproject.toml

- catches and logs all errors from search endpoint

debug: catch and log all errors to search endpoint

---

app/api/api_v1/routers/search.py
app/clients/db/session.py
app/repository/document.py
app/repository/geography.py
app/repository/search.py
app/service/world_map.py
app/telemetry.py
poetry.lock
pyproject.toml

- Adds some more decorators to key functions in the system 
- Adds a utility function to convert complex objects to valid opentelemetry data types when logging/tracing 
- Adds sqlalchemy instrumentation to trace DB call data
Notes:
sure your selected option is …

update: Observe more functions and instrument sqlalchemy (test)

---

families-api/Dockerfile
families-api/app/main.py
families-api/justfile
geographies-api/Dockerfile
geographies-api/app/main.py
geographies-api/justfile
pyproject.toml

- Adds `GITHUB_SHA` env var at build to apis
- Uses a `@related` marker to show where things are coupled as the flow is between `justfile => Docker => App`

feat: add GITHUB_SHA env var to apis

---

geographies-api/README.md
geographies-api/app/router.py
geographies-api/app/s3_client.py
geographies-api/app/service.py
geographies-api/infra/__main__.py
geographies-api/justfile
geographies-api/poetry.lock
geographies-api/pyproject.toml
geographies-api/requirements.txt

Missing boto package causing failure during build
Add resource policy that would allow us to read and post to s3
Minor fixes that were preventing build
Notes:
Please …

chore: add missing boto3 package

---

families-api/app/main.py
families-api/app/test_main.py

- adds most string fields to the `FamilyPublic`
Next up: add linked values like collections etc.

String family fields

---

.github/workflows/deploy-staging.yml
.github/workflows/merge-to-main.yml

Part of componentising our infra
Notes:

Update GH role to use our new role for auto deploys

---

api/infra/__main__.py

Currently production URLs are managed between the `cpr` and `production` AWS accounts.
This means we need
* a subdomain (A record) for `api.cpr.org` in the cpr account
* this points to a `api.cpr.org` zone in the `production` account 
This is a hack until we move over all our domains for production to the production account.
We don't have this issue in staging, as `staging` manages itself.
**This codifies the fix for the bug where @odrakes-cpr was seeing the staging domains resolve in an unpredictable way**
```mermaid
flowchart LR
subgraph production
production.cpr.org
ZONE:api.cpr.org --A--> api.cpr.org --> APICloudFronte
end
subgraph staging
staging.cpr.org
staging.cpr.org --A--> api.staging.cpr.org --> API.staging.CloudFronte
end
subgraph cpr
cpr.org --A--> A:api.cpr.org
A:api.cpr.org …
```

fix: only create zone for api.cpr.org

---

geographies-api/app/service.py

per title add regions to data set we upload to s3

feat: add regions to data set we upload to s3

---

geographies-api/docker-compose.yml
geographies-api/tests/test_service.py

chore: fix command that runs test suite in geo service

chore: fix command that runs test suite

---

backend-api/app/repository/corpus.py

Use subqueries to improve performance on `/config` corpus counts query. This avoids using the `family_status` field, which is a hybrid property and non-indexed field.
We define our own expression to calculate the value of the family_status field, which although is easy for us as humans to read, requires a bunch of CPU as we have to calculate the value of this per row in our database -- and we have over 12,000 documents now! I **think** this is causing super slow query times -- the Otel trace from Grafana around my previous deploy suggested 12 mins for the /config endpoint which is crazy! Because of these super slow query times, we are likely exhausting our connection pool -- and I suspect this may (?) be causing the RDS connections to creep up.
I want to get this on staging to analyse the …

Use subqueries to improve performance on /config corpus counts query

---

.github/workflows/otel.yml

Why: be able to mark deploys on a pretty Grafana dashboard with exact timestamps.

Create otel.yml for GitHub actions

---

families-api/app/main.py

fix: add otel to families-api

---

geographies-api/app/main.py
geographies-api/app/service.py
geographies-api/pyproject.toml
uv.lock

Observe service functions for OTel in geo-api

Feature/app 821 Observe service functions for OTel in geo-api

---

.github/workflows/merge-to-main.yml

- runs just test {service} from the root

fix: run microservices test from root

---

families-api/app/main.py

Updated the following
- alpha3 to code; this is more reflective of the data, as not all values will be alpha3
- have also added the type which is the iso code definition, making it easier to utilise in the front end
- 

Refactor aggregations by document endpoint response

---

families-api/app/main.py

Update the new families api to return attribution url

feat: surface the attribution url in the families api response

---

families-api/app/main.py

- adds documents endpoint
I am going to add testing for the whole suite of endpoints we have here - but trying to get this out swiftly to unblock FE.
depends on #636

feat: document endpoint for families-api

---

families-api/app/main.py

[removed here](https://github.com/climatepolicyradar/navigator-backend/pull/641/files#diff-23546cbe689627cbe55cf86082ead30c91910a7c7cb9cd72dabdc6aaaeb47e35L766)
but used here https://github.com/climatepolicyradar/navigator-frontend/blob/555a51552bddc644721a9990bcdb0b247ec2a3f1/src/hooks/useSubdivisions.ts#L14

fix: reinstate /aggregations/by-geography

---

geographies-api/app/data/cpr_custom_geographies.py
geographies-api/app/model.py
geographies-api/app/router.py
geographies-api/app/service.py
geographies-api/tests/test_main.py

- adds statistics to geographies
- adds [European union](https://app.climatepolicyradar.org/geographies/european-union) to the custom countries
- makes sure we add our custom countries to the list
```json
{
"data": {
"id": "EUR",
"name": "European Union",
"statistics": {
"name": "European Union",
"legislative_process": "The legislative process at the European Union (EU) level involves the European Commission (independent from national governments), the European Parliament (elected by EU citizens), and the Council of the European Union, which represents Member States. Most often, the Commission proposes new legislation, but it is the Council and Parliament together that pass the laws.</div><div>The main forms of EU legislation are directives, regulations and decisions. Directives and …
```

feat: add statistics to Geography

---

.github/dependabot.yml

Group minor and patch updates together so we can auto merge - but make sure major version bumps are raised in separate, individual PRs for traceability and to allow manual testing

Group minor and patch updates

---

.github/workflows/deploy-staging.yml

fix: allow deploy to staging on workflow dispatch

---

backend-api/app/config.py
backend-api/app/service/vespa.py

[Uses the new token auth for vespa](https://github.com/climatepolicyradar/cpr-sdk/commit/6a4846ac4d9089079d3fe747407df42e03ca7756).
Reduce 500 errors in reading the certs from from disk

feat: use token for vespa connection

---

backend-api/app/api/api_v1/routers/summaries.py

404 is not an error, if we don't have it, we don't have it.

fix: you no error, you info

---

backend-api/app/api/api_v1/routers/search.py

We need to use the hostname from the token because the backend has no other way of knowing what site the download request originated from and therefore doesn't know which domain to use for the base URL for the links.

Fix base URL and subject capitalisation for CCC download
